/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AwsCommunityBuilder: typeof import('./components/AwsCommunityBuilder.vue')['default']
    BlogPosts: typeof import('./components/BlogPosts.vue')['default']
    CareerTimeline: typeof import('./components/CareerTimeline.vue')['default']
    GitHubTrophies: typeof import('./components/GitHubTrophies.vue')['default']
    PortfolioHero: typeof import('./components/PortfolioHero.vue')['default']
    ProjectsSection: typeof import('./components/ProjectsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsSection: typeof import('./components/SkillsSection.vue')['default']
  }
}
